/**
 * Pizzeria Public API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Offer { 
    id?: number;
    image: string;
    name: { [key: string]: string; };
    description: { [key: string]: string; };
    caveat: { [key: string]: string; };
}

