export * from './anonymousOrdersAPI.service';
import { AnonymousOrdersAPIService } from './anonymousOrdersAPI.service';
export * from './offerAPI.service';
import { OfferAPIService } from './offerAPI.service';
export * from './productAPI.service';
import { ProductAPIService } from './productAPI.service';
export * from './storeAPI.service';
import { StoreAPIService } from './storeAPI.service';
export * from './utilAPI.service';
import { UtilAPIService } from './utilAPI.service';
export const APIS = [AnonymousOrdersAPIService, OfferAPIService, ProductAPIService, StoreAPIService, UtilAPIService];
