/**
 * Pizzeria User API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterDTO {
  name: string;
  email: string;
  matchingEmail: string;
  contactNumber: number;
  password: string;
  matchingPassword: string;
}

