/**
 * Pizzeria Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderStatisticsByState } from './orderStatisticsByState';


export interface OrderStatistics { 
    statisticsByState: Array<OrderStatisticsByState>;
}

