/**
 * Pizzeria Business API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {CartItemDTO} from './cartItemDTO';


export interface CartDTO {
    totalQuantity: number;
    totalCost: number;
    totalCostOffers: number;
    cartItems: Array<CartItemDTO>;
}

