/**
 * Pizzeria Business API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderDetailsDTO { 
    deliveryTime: string;
    paymentMethod: string;
    billToChange?: number;
    comment?: string;
    storePickUp: boolean;
    changeToGive?: number;
}

