/**
 * Pizzeria Fabulosa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Address { 
    id?: number;
    street: string;
    number: number;
    details?: string;
}

