/**
 * Pizzeria Fabulosa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderDetailsDTO } from './orderDetailsDTO';
import { CartDTO } from './cartDTO';


export interface NewUserOrderDTO { 
    addressId: number;
    orderDetails: OrderDetailsDTO;
    cart: CartDTO;
}

