/**
 * Pizzeria Fabulosa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderSummaryDTO { 
    id: number;
    formattedCreatedOn: string;
    paymentMethod: string;
    quantity: number;
    cost: number;
    costAfterOffers: number;
}

