/**
 * Pizzeria Fabulosa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderSummaryDTO } from './orderSummaryDTO';


export interface OrderSummaryListDTO { 
    orderList: Array<OrderSummaryDTO>;
    totalPages: number;
    pageSize: number;
    totalElements: number;
    hasNext: boolean;
}

