/**
 * Pizzeria Fabulosa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';


export interface ProductListDTO { 
    productList: Array<Product>;
    totalPages: number;
    pageSize: number;
    totalElements: number;
    hasNext: boolean;
}

