/**
 * Pizzeria Fabulosa API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';


export interface Store { 
    id?: number;
    image: string;
    name: string;
    phoneNumber: number;
    schedule: { [key: string]: string; };
    address: Address;
}

