/**
 * Pizzeria Fabulosa API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {HttpClient, HttpContext, HttpEvent, HttpParams, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';

// @ts-ignore
import {ResponseDTO} from '../model/responseDTO';

// @ts-ignore
import {BASE_PATH, COLLECTION_FORMATS} from '../variables';
import {Configuration} from '../configuration';
import {BaseService} from '../api.base.service';


@Injectable({
  providedIn: 'root'
})
export class LoginAPIService extends BaseService {

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string | string[], @Optional() configuration?: Configuration) {
    super(basePath, configuration);
  }

  /**
   * @param username Email
   * @param password Password
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public login(username: string, password: string, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'text/plain' | 'application/json',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any>;
  public login(username: string, password: string, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'text/plain' | 'application/json',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<any>>;
  public login(username: string, password: string, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'text/plain' | 'application/json',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<any>>;
  public login(username: string, password: string, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'text/plain' | 'application/json',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (username === null || username === undefined) {
      throw new Error('Required parameter username was null or undefined when calling login.');
    }
    if (password === null || password === undefined) {
      throw new Error('Required parameter password was null or undefined when calling login.');
    }

    let localVarQueryParameters = new HttpParams({encoder: this.encoder});
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
      <any>username, 'username');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
      <any>password, 'password');

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'text/plain',
      'application/json'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/login`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<any>('post', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        transferCache: localVarTransferCache,
        reportProgress: reportProgress
      }
    );
  }

}
