/**
 * Pizzeria Assets API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Offer} from './offer';


export interface OfferListDTO {
  offers: Array<Offer>;
}

