/**
 * Pizzeria Assets API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Product { 
    id?: number;
    type: string;
    image: string;
    name: { [key: string]: string; };
    description: { [key: string]: Array<string>; };
    formats: { [key: string]: { [key: string]: string; }; };
    prices: { [key: string]: number; };
    allergens: { [key: string]: Array<string>; };
}

