/**
 * Pizzeria Assets API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Store } from './store';


export interface StoreListDTO { 
    stores: Array<Store>;
}

